name: camerademo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.2.0
  splashscreen: ^1.3.5
  app_settings: 4.1.5
  camera: ^0.9.4+4
  video_player: ^2.1.14
  flutter_slider_drawer: ^2.1.0
  scroll_snap_list: ^0.8.6
  image_gallery_saver: ^1.7.1
  dio: ^4.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # CJK인코딩 지원
  charset_converter: ^2.0.0
  # String 포매팅
  sprintf: ^6.0.0
  intl: ^0.17.0
  # 하단탭
  persistent_bottom_nav_bar: ^4.0.2
  circular_bottom_navigation: ^2.0.0
  # 커스텀 다이얼로그
  awesome_dialog: ^2.1.2
  # 통신용
  http: ^0.13.4
  # 통신용 JSON 생성
  json_annotation: ^4.4.0
  # 통신용 JSON 생성
  json_serializable: ^6.1.3
  # 이미지 캐시사용
  cached_network_image: ^3.2.0
  # URL 이동
  url_launcher: ^6.0.17
  # 토스트메세지
  fluttertoast: ^8.0.9
  # 더보기
  auto_size_text: ^3.0.0              # 텍스트 AutoSize
  flutter_vertical_marquee: ^0.2.3    # 세로로 흘러가는 효과
  flutter_install_app_plugin: ^0.4.3  # 앱 설치화면으로 이동
  image_cropper: ^1.4.1               # 이미지 크롭
  image_picker: ^0.8.4+4              # 이미지 선택
  smooth_page_indicator: ^1.0.0+2     # 페이지 인디케이터 (하단 점)
  flutter_share: ^2.0.0               # 공유
  permission_handler: ^8.3.0          # ios 권한 허용
  path_provider: ^2.0.0               # 이미지 path
  chips_choice: ^2.0.1                # 관심메뉴 설정용 태그c
  carousel_slider: ^4.0.0             # 리스트 하단 페이지 (광고)
  marquee: ^2.2.0                     # 흘러가는 효과
  flutter_staggered_grid_view: ^0.4.1
  syncfusion_flutter_charts: ^19.4.38
  pull_to_refresh: ^2.0.0
  flutter_rounded_date_picker: ^2.0.2 # 날짜 선택 다이얼로그
  shared_preferences: ^2.0.11         # 로컬저장
  simple_url_preview: ^3.0.1          # URL 팝업
  convex_bottom_bar: ^3.0.0          # 하단탭
  local_auth: ^1.1.9                  # 로컬인증 (지문인증 등..)
  expansion_tile_card: ^2.0.0         # 펼쳐지는 리스트 (공지사항)
  flutter_joystick: ^0.0.1            # 조이스틱 위젯
  flutter_staggered_animations: ^0.1.2 # 리스트 애니메이션
  get: ^3.26.0                        # GetX
  encrypt: ^5.0.1                     # 암호화


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
